### ISSUE TITLE
Table of contents direct linking

### ISSUE THREAD

**Issue by queryluke** [blakearchive/erdman#15]
Some do not go to correct headings

**Comment by queryluke** [comment]
will be fixed with #28

**Comment by ghost** [comment]
@queryluke i noticed some of the contents like some of the ones under Songs of Innocence aren't working. for example, The Little Boy lost. should we add page number attributes to all \<head\> tags, too?

**Comment by queryluke** [comment]
From the updated erdman xml
```
<div4 page="10" n="8" type="poem" id="b1.5.1.8">
  <pb n="11"/>
  <milestone rend="left" n="13" unit="SONGS"/>
  <head rend="center">
    The Little Boy lost
    <ptr target="tn11.1"/>
  </head>
  ...
</div4>
```
You've given it the wrong page number. "The Little Boy Lost" starts on page 11.
