### ISSUE TITLE
only the selected item in table of contents should be highlighted (not all expanded items)

### ISSUE THREAD

**Issue by ghost** [blakearchive/erdman#23]

**Comment by queryluke** [comment]
This is a bit tricky. In the previous system, clicking on a heading loaded that section and ONLY that section. But now you can scroll past the section you've jumped to. Meaning the selected tab would not apply. Hence, I was using the dark background to indicate open lists. I'll look into other options

**Comment by queryluke** [comment]
Going to use scrollspy for this. Got it working but am currently blocked by #28. Once all the page headings have a page number target I can refactor the scrollspy branch and merge
