### ISSUE TITLE
double line titles should be made into one with a colon separating the strings from each line

### ISSUE THREAD

**Issue by ghost** [blakearchive/erdman#25]
example: 

in the book:
For Children
The Gates of Paradise

is rendered in the Table of Contents: For ChildrenThe Gates of Paradise 

it should be: For Children: The Gates of Paradise

**Comment by queryluke** [comment]
See http://erdman-qa.lib.unc.edu/#7 (Shewing the Two Contrary States of the Human Soul) is showing up as the title in the header

**Comment by queryluke** [comment]
Issue is a double <head> tag in the BADs

**Comment by queryluke** [comment]
I merged in your commit from yesterday, but it looks like the only file that was updated was data.js, not transform.py. Looking at https://github.com/blakearchive/erdman/commit/ab55ed3854c5a174737b8c570454d5c0f71a10fd, I don't see the change. Did it get commited?
