### ISSUE TITLE
TOC is not working

### ISSUE THREAD

**Issue by ghost** [blakearchive/erdman#40]
@queryluke luke, the TOC does not seem to be working properly. i can't tell if it's because we've put bad page numbers in or if it's a problem with the code. when you get a chance, can you look into this. it's pretty wonky all over the place

**Comment by ghost** [comment]
one example: Milton

clicking on Milton in the TOC opens up page 94, not 5.

in the code it looks like: `<pb n="95"/><milestone rend="left" n="i [1]" unit="PLATE"/><head rend="center">MILTON<ptr target="tn95.1"/><lb/>a Poem in 2 Books</head>`

**Comment by queryluke** [comment]
You have the wrong page numbers in the xml. See below, the same point in the code you're referring to:
```
<div2 page="94" n="15" type="poem" id="b1.15">
<pb n="95"/>
<milestone rend="left" n="i [1]" unit="PLATE"/>
<head rend="center">MILTON<ptr target="tn95.1"/>
```

`<div2>` has a page association of 94. But the poem associate with `<div2>`, Milton, starts on page 95.

**Comment by queryluke** [comment]
I will say, however, that there is a completely different way to handle the TOC. The main issue right now is that multiple headers are linked to a single page. That's why you're getting the "jumpy" feel with the highlighted items. It also makes it impossible to jump directly to the subsection of a page.

An alternate solution would be to load the entire document. The initial load time would be pretty slow (maybe 5-10 seconds), but it would solve a lot of other problems, specifically with the TOC.

**Comment by ghost** [comment]
hmm, interesting. could we display pages as they're loaded during the full loading process? or 20 pages or so?

**Comment by queryluke** [comment]
I'm sure that's possible. But I won't have time to figure out before monday.

**Comment by ghost** [comment]
ok. i've uploaded new xml's with the page numbers corrected and deployed, but it seems there's still the 1-page back problem

**Comment by ghost** [comment]
i think the problem is that the `<div page=...>` tags in many cases come before the page break (`<pb>`) tags

**Comment by queryluke** [comment]
I've just just pushed a "whole-hog" version to qa: http://erdman-qa.lib.unc.edu/ You'll either need to clear your cache (cmd+shift+r), or open in an incognito tab. I've getting load times between 2-5s.

The main benefit is that the TOC behavior is much more predictable. It jumps to the actual section (not just the page).

But there are some issues:
- page load time (we can make the loading text more apparent with an animation)
- will still require some XML editing. In this case, it looks like the main entries,`<div1>`, all link to the prior page. So the amount of editing should be minor, i think we'll only need to move the `<pb ...>` tags immediately following `<div1>`
- no scrollspy (i.e., highlighting as you scroll). There are too many headers and the plugin can't keep up. So I had to turn this off. However, the previous iteration of the scroll spy wasn't working very well anyway.

Please take a look and discuss with everyone. I'll need to make some additional changes to this branch (search linking broke when I implemented it). But I didn't want to make all these changes if lacking a scrollspy and the page load time were blockers.

To be blunt: it's this "whole-hog" version or what's currently on production, http://erdman.lib.unc.edu. I can manually update the data.js file which will fix the incorrect TOC linking, but you'll still have the issue of a buggy scrollspy (which I can turn off), page only linking, and delayed page loads (the split second after you scroll to a page when it's completely white).

**Comment by ghost** [comment]
ok, move the `<pb>` tags where? to before the `<div>`?

**Comment by ghost** [comment]
ok, i uploaded new XML's with the `<pb>` tags moved to before the `<div>` tags

**Comment by ghost** [comment]
and all we need is an icon indicating loading while the whole thing is getting loaded

**Comment by queryluke** [comment]
You do want to take the approach of loading the entire document then?

**Comment by ghost** [comment]
yeah, i think it's better. hopefully it's easy to add a temporary "Loading..." indication

**Comment by ghost** [comment]
maybe in the center of the right column
