### ISSUE TITLE
initially open URL showing Cover page

### ISSUE THREAD

**Issue by ghost** [blakearchive/erdman#50]

**Comment by queryluke** [comment]
Do you mean the cover image? If so, where you do you want the loading spinner to go?

It would actually be helpful if you could make a very low-fi wireframe of what you want the initial page load to look like

**Comment by ghost** [comment]
no, keep the loading spinner. but initially display the 'Cover' page under Preliminaries. see the TOC. that ought to have the cover image on it.

**Comment by ghost** [comment]
ah, i see you put the cover image up. yes, open to that page initially (page I --the letter I).
