### ISSUE TITLE
git pull

### ISSUE THREAD

**Issue by ghost** [blakearchive/erdman#55]
@queryluke just tried to add a google html file so that i can get google to index erdman. i put it in client/dist and tried to deploy. got this error, the same error i was getting when trying to deploy the archive. i think it needs to be a git pull after checking out python26 instead of a git fetch at the beginning.

G [4a5ee119] Command: cd ../erdman; git fetch; git checkout master; git pull origin master; git checkout python26; git merge --no-ff -m 'Merge master into python26' master; git push origin python26; git checkout master;
DEBUG [4a5ee119] 	Already on 'master'
DEBUG [4a5ee119] 	Your branch is up-to-date with 'origin/master'.
DEBUG [4a5ee119] 	From https://github.com/blakearchive/erdman
DEBUG [4a5ee119] 	 * branch            master     -> FETCH_HEAD
DEBUG [4a5ee119] 	Already up-to-date.
DEBUG [4a5ee119] 	Switched to branch 'python26'
DEBUG [4a5ee119] 	Your branch and 'origin/python26' have diverged,
DEBUG [4a5ee119] 	and have 47 and 7 different commits each, respectively.
DEBUG [4a5ee119] 	  (use "git pull" to merge the remote branch into yours)
DEBUG [4a5ee119] 	Already up-to-date.
DEBUG [4a5ee119] 	To https://github.com/blakearchive/erdman.git
DEBUG [4a5ee119] 	 ! [rejected]        python26 -> python26 (non-fast-forward)
DEBUG [4a5ee119] 	error: failed to push some refs to 'https://github.com/blakearchive/erdman.git'
DEBUG [4a5ee119] 	hint: Updates were rejected because the tip of your current branch is behind
DEBUG [4a5ee119] 	hint: its remote counterpart. Integrate the remote changes (e.g.
DEBUG [4a5ee119] 	hint: 'git pull ...') before pushing again.
DEBUG [4a5ee119] 	hint: See the 'Note about fast-forwards' in 'git push --help' for details.
DEBUG [4a5ee119] 	Switched to branch 'master'
DEBUG [4a5ee119] 	Your branch is up-to-date with 'origin/master'.

**Comment by ghost** [comment]
the git pull after checking out python26 worked

**Comment by queryluke** [comment]
changes are made, you can update your local deploy repos by doing a git pull within archive-deploy and erdman-deploy
